name: Build & push Docker image to cloud provider
on:
  workflow_dispatch:
    inputs:
      ImageName:
        description: "The name you want to give the Docker image built"
        required: false
        default: "my-cool-docker-image"
      CloudProvider:
        description: "The cloud provider you want to push the Docker image to [AWS or GCP]"
        required: true
        
env:
  REGISTRY: ${{ github.event.inputs.CloudProvider == 'AWS' && '[aws-account-number].dkr.ecr.[region].amazonaws.com' || github.event.inputs.CloudProvider == 'GCP' && 'gcr.io' }}
  USERNAME: ${{ github.event.inputs.CloudProvider == 'AWS' && '' || github.event.inputs.CloudProvider == 'GCP' && '_json_key' }}
  USE_PASSWORD: ${{ github.event.inputs.CloudProvider == 'AWS' && 'false' || github.event.inputs.CloudProvider == 'GCP' && 'true' }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.CloudProvider }}

    steps:
      - name: Validate input
        if: github.event.inputs.CloudProvider != 'AWS' && github.event.inputs.CloudProvider != 'GCP'
        run: |
          echo "Error! Please choose either AWS or GCP as the cloud provider."
          exit 1
        
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: sandbox-327002/${{ github.event.inputs.ImageName }}
          tags: latest
          registry: ${{ env.REGISTRY }}
          dockerfile: Dockerfile
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
